
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jimbo",
  "secret": "applesauce"
}

###

POST http://localhost:4000/register
Content-Type: application/json

{
  "username": "Jimbo",
  "secret": "applesauce",
  "email": "jim@gmail.com",
  "first_name": "jim@gmail.com",
  "last_name": "jim@gmail.com"
}

